HEADER:
  label: "About me"

PRESENTATION:
  description: |
    Sophisticated learner, Creative solo developer with hands on every stack.
DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Gamedev"
      icon: "config/assets/icons/mobile.svg"
      description: "Actively studying and involving in Gamedevelopment."
    - title: "Scripting"
      icon: "config/assets/icons/code.svg"
      description: "Automation and task scripting using Python to enhance efficiency and productivity."
    - title: "UI/UX Designing"
      icon: "config/assets/icons/compass.svg"
      description: "Intuitive and visually appealing user interfaces and user experiences."
    - title: "Web Development"
      icon: "config/assets/icons/laptop-code.svg"
      description: "Involved in full-stack Web App Development"

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "MongoDB"
      icon: "config/assets/icons/mongodb.svg"
    - title: "Express"
      icon: "config/assets/icons/express.svg"
    - title: "React"
      icon: "config/assets/icons/react.svg"
    - title: "Node.js"
      icon: "config/assets/icons/nodejs.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Figma"
      icon: "config/assets/icons/figma.svg"
    - title: "Firebase"
      icon: "config/assets/icons/firebase.svg"
    - title: "Node.js"
      icon: "config/assets/icons/nodejs.svg"
    - title: "Dart"
      icon: "config/assets/icons/dart.svg"
    - title: "HTML"
      icon: "config/assets/icons/html.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
