HEADER:
  label: "Certifications"

POSTS:
  - title: "MERN STACK"
    category: "Traning"
    subtitle: "Completed at Broadway Infosys"
    published: "2025-06-13"
    image: "config/assets/posts/MERN-STACK.png"
    url: "https://drive.google.com/file/d/1kPo6n_Q7OGrxLezwLYCMNOJGIPkYsQjO/view?usp=sharing"

  - title: "Python With Data Science"
    category: "Training"
    subtitle: "Training at Kantipur Engineering College"
    published: "2023-07-23"
    image: "config/assets/posts/Data.jpg"
    url: "https://drive.google.com/file/d/1oMpAFOCZBtOgHSLLIYaSbusaE8MXeyrB/view?usp=sharing"

  - title: "Postman API Fundamentals Student Expert"
    category: "Training"
    subtitle: "Postman API Fundamentals Training"
    published: "2025-06-19"
    image: "config/assets/posts/postman.jpg"
    url: "https://api.badgr.io/public/assertions/2E7UuyLMSSO1taz8t6lw8w?identity__email=mallakebin%40gmail.com"

  - title: "Build a Movie Search App"
    category: "Crash Course"
    subtitle: "Course Completed in Scrimba"
    published: "2025-01-17"
    image: "config/assets/posts/Movie.png"
    url: "https://drive.google.com/file/d/1ovCo-bvWQGAgwSRAP-yGY76XdCRiXiBT/view?usp=sharing"
