HEADER:
  label: "Certifications"

POSTS:
  - title: "MERN STACK"
    category: "Traning"
    subtitle: "Completed at Broadway Infosys"
    published: "2025-06-13"
    image: "config/assets/posts/MERN-STACK.png"
    url: "https://drive.google.com/file/d/1kPo6n_Q7OGrxLezwLYCMNOJGIPkYsQjO/view?usp=sharing"

  - title: "Python With Data Science"
    category: "Training"
    subtitle: "Training at Kantipur Engineering College"
    published: "2023-07-23"
    image: "config/assets/posts/Data.jpg"
    url: "https://drive.google.com/file/d/1oMpAFOCZBtOgHSLLIYaSbusaE8MXeyrB/view?usp=sharing"

  - title: "Build a Movie Search App"
    category: "Crash Course"
    subtitle: "Course Completed in Scrimba"
    published: "2025-01-17"
    image: "config/assets/posts/Movie.png"
    url: "https://drive.google.com/file/d/1ovCo-bvWQGAgwSRAP-yGY76XdCRiXiBT/view?usp=sharing"

  - title: "UI interactions of the week"
    category: "Design"
    subtitle: "Discover the most engaging UI interactions of the week that are driving user experiences forward."
    published: "2022-02-23"
    image: "config/assets/posts/blog-4.jpg"
    url: "https://dev.to"

  - title: "The Forgotten Art Of Spacing"
    category: "Design"
    subtitle: "Learn about the importance of spacing in design and how it can elevate the visual hierarchy of your work."
    published: "2022-02-23"
    image: "config/assets/posts/blog-5.jpg"
    url: "https://medium.com"

  - title: "Design Digest #79"
    category: "Design"
    subtitle: "This edition covers the latest insights into design practices and tools you need to know."
    published: "2022-02-23"
    image: "config/assets/posts/blog-6.jpg"
    url: "https://hashnode.com"
