# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Full Stack Developer"
  name: "Kebin Malla"
  username: "kevin272" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar2.png"

INFO:
  - label: "Email"
    value: "mallakebin@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+977-9862394960"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "June 26, 2003"
    icon: "calendar-outline"
  - label: "Location"
    value: "New Baneswor, Kathmandu, Nepal"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://www.facebook.com/kebin.malla/"
  - icon: "logo-twitter"
    url: "https://x.com/DevilKevin2"
  - icon: "logo-instagram"
    url: "https://www.instagram.com/dvl_kvn/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/kebinmalla/"
  - icon: "logo-github"
    url: "https://github.com/kevin272"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
