HEADER:
  label: "Portfolio"
PROJECTS:
  - title: "SajhaBiz"
    category: "MERN Stack"
    image: null
    url: null
  - title: "Javascript Simulation Projects"
    category: "Javascript"
    image: null
    url: null
  - title: "Movie Search App"
    category: "Reactjs, TailwindCSS"
    image: null
    url: null
  - title: "Debug Adventure"
    category: "C#, Unity2D"
    image: null
    url: null
  - title: "Nepali-English Language Translator"
    category: "Transformers, FFMPEG, PyTorch, Hugging Face, MMS, M2M100"
    image: null
    url: null
  - title: "Responsive Google Forms"
    category: "HTML, CSS, PHP, JavaScript, MySQL"
    image: null
    url: null
  - title: "Image Recognition Bot"
    category: "PyGUI, Python"
    image: null
    url: null
  - title: "Collaborative Code Editor"
    category: "HTML, CSS, JS"
    image: null
    url: null
  - title: "Credit Card validator"
    category: "C++"
    image: null
    url: null
  - title: "Qbasic Pokemon Game"
    category: "Qbasic"
    image: null
    url: null
