HEADER:
  label: "Portfolio"
PROJECTS:
  - title: "SajhaBiz"
    category: "WebDev"
    image: "config/assets/projects/Sajhabiz.png"
    url: "https://github.com/kevin272/MERN"
  - title: "Javascript Simulation Projects"
    category: "Misc"
    image: null
    url: null
  - title: "Movie Search App"
    category: "WebDev"
    image: null
    url: null
  - title: "Debug Adventure"
    category: "Gamedev"
    image: "config/assets/projects/Debugadv.png"
    url: "https://dvlkvn.itch.io/debugadventure"
  - title: "Nepali-English Language Translator"
    category: "Misc"
    image: "config/assets/projects/Translator.jpg"
    url: "https://huggingface.co/spaces/bishaltwr/Ne-En-Trn"
  - title: "Responsive Google Forms"
    category: "WebDev"
    image: "config/assets/projects/Forms.png"
    url: "https://makethis.great-site.net/?i=2"
  - title: "Image Recognition Bot"
    category: "Misc"
    image: ""
    url: null
  - title: "Collaborative Code Editor"
    category: "WebDev"
    image: "config/assets/projects/Code.png"
    url: null
  - title: "Credit Card validator"
    category: "Misc"
    image: "config/assets/projects/Card.png"
    url: null
  - title: "Qbasic Pokemon Game"
    category: "Misc"
    image: null
    url: null
  - title: "MERN DEMO"
    category: "WebDevelopment"
    image: "config/assets/projects/Demo.png"
    url: null