HEADER:
  label: "Portfolio"
PROJECTS:
  - title: "SajhaBiz"
    category: "WebDev"
    image: "config/assets/projects/Sajhabiz.png"
    url: "https://github.com/kevin272/MERN"
  - title: "ChatR"
    category: "WebDev"
    image: "config/assets/projects/ChatR.png"
    url: "https://chatr.kebinmalla.com.np"
  - title: "Noteify"
    category: "WebDev"
    image: "config/assets/projects/Noteify.png"
    url: "https://noteify.kebinmalla.com.np"
  - title: "Debug Adventure"
    category: "Gamedev"
    image: "config/assets/projects/Debugadv.png"
    url: "https://dvlkvn.itch.io/debugadventure"
  - title: "Nepali-English Language Translator"
    category: "Misc"
    image: "config/assets/projects/Translators.jpg"
    url: "https://huggingface.co/spaces/bishaltwr/Ne-En-Trn"
  - title: "Responsive Google Forms"
    category: "WebDev"
    image: "config/assets/projects/Forms.png"
    url: "https://makethis.great-site.net/?i=2"
  - title: "Collaborative Code Editor"
    category: "WebDev"
    image: "config/assets/projects/Code.png"
    url: null
  - title: "Credit Card validator"
    category: "Misc"
    image: "config/assets/projects/Card.png"
    url: null
  - title: "MERN DEMO"
    category: "WebDev"
    image: "config/assets/projects/merndemo.png"
    url: "https://merndemo.kebinmalla.com.np"
  - title: "Movie Search App"
    category: "WebDev"
    image: "config/assets/projects/movies.png"
    url: null
  - title: "Javascript Simulation Projects"
    category: "Misc"
    image: null
    url: null
